name: Update README

# This workflow automatically updates the README.md file daily at 2:00 AM UTC
# by cloning it from the fabriziosalmi/repos repository.
# It can also be triggered manually using the "Run workflow" button in GitHub Actions.

on:
  schedule:
    # Run daily at 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Manual trigger support

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Download latest README
        run: |
          curl -o README.md https://raw.githubusercontent.com/fabriziosalmi/repos/refs/heads/main/README.md
          
      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet README.md || echo "changed=true" >> $GITHUB_OUTPUT
          
      - name: Commit and push changes
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git commit -m "chore: update README.md from repos repository"
          git push
